### ISSUE TITLE
Error on host with PHP 5.6

### ISSUE THREAD

**Issue by GJSchaller** [Xeroday/cPanel-Auto-Backup#1]
When running this script on a host using PHP 5.5.x, everything works fine.

When running on the same host with PHP 5.6.x, the following error occurs:

HTTP/1.1 301 Moved Server: cpsrvd/11.42.1.21 Connection: close Content-length: 120 Location: https://serv01.c7616.sgvps.net:2083/ Content-type: text/html; charset="utf-8"

Additionally, if $secure = true, another error occurs:

Failed to open socket connection.

**Comment by GJSchaller** [comment]
The same issue is happening on PHP 7.0.

**Comment by GJSchaller** [comment]
Hello, this has still been an issue on PHP 5.6 and 7.0 - I can help by giving you a testing environment to play with, if you need help updating this to work with more recent versions.

Thank you!

**Comment by Xeroday** [comment]
If you have cPanel set up on PHP 7.0 and could send over a test account to eric@xeroday.org I could look at it!

**Comment by Xeroday** [comment]
Thanks @GJSchaller for a dev environment. I've updated the [website](https://www.ericzhang.me/projects/cpanel-auto-backup/) and put the updated code in this repo.
